Repository dtcenter/METcalcpy, pull requests merged in 2020-10, with the labels that each got.

#35 Feature 27 Difficulty Index
  docs/README_difficulty_index.txt
  metcalcpy/calc_difficulty_index.py
  metcalcpy/piecewise_linear.py
  test/test_calc_difficulty_index.py
  test/test_lon_360_to_180.py
Labels: associated: METplotpy, priority: high, requestor: Navy/NRL, type: new feature

#38 Task 37 diff_index_version
  docs/README_difficulty_index.txt
  metcalcpy/calc_difficulty_index.py
  test/test_calc_difficulty_index.py
Labels: associated: METplotpy, priority: high, requestor: Navy/NRL

#39 Feature 33 s2s convert lon indices
  docs/utils/README_util.rst
  metcalcpy/util/utils.py
  test/test_convert_lon_indices.py
Labels: associated: METplotpy, component: common utils, priority: high, requestor: NCAR/RAL
